[book]
authors = ["Acheul"]
language = "en"
multilingual = false
src = "src"
title = "Ex-mdbook"

[build]
build-dir = "../docs"

[output.html]
theme = "theme"
no-section-label = true
git-repository-url = "https://github.com/acheul/mdbook-collector"
additional-js = ["adds/tags.js"]
additional-css = ["adds/tags.css"]
site-url = "/mdbook-collectors/"

[output.html.print]
enable = false

[preprocessor.collector]
input_type = "json" # "yaml" "toml"
# marker = "collect"
# save_path = "collect.json"
# add_title = true

[preprocessor.tagger]
# marker = "tags"
# tag2posts_path = "tag2posts.json"
# post2tags_path = "post2tags.json"
# split = ";" # ","

[preprocessor.tocjs]
# save_dir = "lib"
# theme_dir = "theme"
# block_marker_id = "tock"
# wing_marker_id = "tocw"
base_url = "/mdbook-collectors/"